### ISSUE TITLE
how to match path under any parent directory

### ISSUE THREAD

**Issue by craighurley** [actions/labeler#10]
Hello,

I have the following example folder structure

```
app/
└── subdir
    └── config
        └── subdir
            └── test.yaml
```

My workflow action looks like this:

```
name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

My goal is to be able to label PRs when certain files are found under certain sub-directories with the caveat that the target sub-directories may appear under _any_ parent directory in the repo.

This `labeler.yaml` works and results in a label being applied, but I have to specifically name the parent directory.

```
config:
- app/**/config/**/*.yaml
```

This `labeler.yaml` does not work/no label is applied:

```
config:
- ./**/config/**/*.yaml
```

These 2 variants of `labeler.yaml` fail with a similar error:

```
config:
- **/**/config/**/*.yaml
```

```
config:
- */**/config/**/*.yaml
```

... where the error is:

```
##[error]YAMLException: unidentified alias "*/config/**/*.yaml" at line 5, column 22:
    - **/config/**/*.yaml
                         ^
##[error]unidentified alias "*/config/**/*.yaml" at line 5, column 22:
    - **/config/**/*.yaml
                         ^
##[error]Node run failed with exit code 1 
```

Can someone advise if what I am trying to do is possible, if so, what should the glob pattern look like?

Thanks
