### ISSUE TITLE
Labeler assigning wrong label

### ISSUE THREAD

**Issue by TurnrDev** [actions/labeler#103]
I'm not sure if my yml file is wrong or something but labeller seems to be assigning the `backend` label to everything.

Here's my file: [.github/labeler.yml](https://github.com/TrainerDex/Website/blob/e0727423e5c6e84540585c19e08f099e721b53b7/.github/labeler.yml)
```yml
npm:
  - package.json
  - package-lock.json

pip:
  - requirements.txt
  - requirements-dev.txt

dependencies:
  - package.json
  - package-lock.json
  - requirements.txt
  - requirements-dev.txt

frontend:
  - 'assets/**/*'
  - 'trainerdex/templates/**/*'
  - 'trainerdex/static/**/*'

backend:
  - 'community/admin.py'
  - 'community/models.py'
  - 'config/settings.py'
  - 'config/urls.py'
  - 'trainerdex/api/**/*'
  - 'trainerdex/admin.py'
  - 'trainerdex/urls.py'
  - 'trainerdex/models.py'
  - '!trainerdex/pogo_assets/strings.py'
  - '!static/pogo_assets/**/*'

migrations:
  - 'community/migrations/*'
  - 'trainerdex/migrations/*'
```

As you can see for TrainerDex/Website#55, labeler [assigned](https://github.com/TrainerDex/Website/pull/55#event-3812911416) `backend` to a PR that only changed `package.json` and `package-lock.json`. 

Is my config wrong?

**Comment by derkinderfietsen** [comment]
It's because of the following lines:
> ```yaml 
>   - '!trainerdex/pogo_assets/strings.py'
>   - '!static/pogo_assets/**/*'

Since the default behavior is to [checkAny](https://github.com/actions/labeler/blob/main/src/main.ts#L186), these lines will match every changed file, for example, `something` matches `!trainerdex/pogo_assets/strings.py` because it really isn't the same.

According to the documentation. you can try the following config instead:
```yaml
backend:
  any:
    - 'community/admin.py'
    - 'community/models.py'
    - 'config/settings.py'
    - 'config/urls.py'
    - 'trainerdex/api/**/*'
    - 'trainerdex/admin.py'
    - 'trainerdex/urls.py'
    - 'trainerdex/models.py'
  all:
    - '!trainerdex/pogo_assets/strings.py'
    - '!static/pogo_assets/**/*'
```
