### ISSUE TITLE
Labeler is syncing labels when sync-labels property is false

### ISSUE THREAD

**Issue by joncolas** [actions/labeler#104]
Having created a branch with an empty commit, I create a PR with some tags added manually, then labeler github action is executed and removes (synchronize) all labels that I have defined in the file labeler.yml complying with the file rules.

I tried with `sync-labels` unset and set to `false`.

github action log:
```
Run actions/labeler@main
  with:
    repo-token: ***
    sync-labels: false
    configuration-path: .github/labeler.yml
```

![image](https://user-images.githubusercontent.com/8049798/94809720-4edd6300-03f3-11eb-91fc-18355f31e56c.png)

I think this should not happen with the `sync-labels` set to `false`, any advice?
