### ISSUE TITLE
Labeler is not labeling PRs

### ISSUE THREAD

**Issue by Kitzunu** [actions/labeler#107]
Hey! 

I am using this action on an open-source repository with these settings:

```yml


DB:
  - data/**/*.sql

CORE:
  - any: ['src/**/*.cpp', 'src/**/*.h', '!src/server/scripts/*']

Script:
  - src/server/scripts/**/*.cpp
  - src/server/scripts/**/*.h

Documentation:
  - ./*.md

Bash:
  - ./*.sh

Cmake:
  - ./*.cmake

Workflow:
  - .github/workflows/*
```
```yml
name: "Pull Request Labeler"
on: [pull_request]

jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        sync-labels: true
```

On the initial PR to implement this it did label on what was changed no problems, but now when I update PRs to latest master the action will run, however, it will not label anything.

Is there something in my settings that I have messed up for it to correctly label PRs?
