### ISSUE TITLE
How to only add label, not remove when PR is opened?

### ISSUE THREAD

**Issue by pllim** [actions/labeler#112]
I have a labeler action set up for when PR is opened, using all your default settings. The [labeler YAML](https://github.com/astropy/astropy/blob/master/.github/labeler.yml) is set up as such (relevant parts listed below):

```yaml
Docs:
  - docs/*

coordinates:
  - '**/coordinates/**/*'
```

When astropy/astropy#11023 was opened, the only file changed was `docs/coordinates/apply_space_motion.rst`. By the labeler logic, it should apply `Docs` and `coordinates`.

**However,** the PR author already manually applied `Docs` label at creation time. As a result, the labeler ended up *removing* the `Docs` label. Is this a bug? How do I tell it to simply no-op when a label that should be applied is already there?

![Screenshot 2020-11-10 234620](https://user-images.githubusercontent.com/2090236/98769915-f5cbfc00-23ae-11eb-9c54-7451597de23f.jpg)

Hope you can help and thanks for such a useful action!

**Comment by pllim** [comment]
Strangely enough, accidental removal did not happen for astropy/astropy#11028 when the file changed was only `docs/conf.py` and `Docs` label was also applied manually when PR was opened.

**Comment by makecir** [comment]
There hasn't been much progress in the conversation, but I also want to solve this problem.
By removing the manually attached tags, the benefits gained by labelar are diminished.

**Comment by ericdallo** [comment]
Any news here?

**Comment by adam-azarchs** [comment]
It looks like the problem is https://github.com/actions/labeler/blob/590628261a373c5bb0bbfbb751555f06766aace0/src/labeler.ts#L18
which is not correct because the default value is `"false"`, and `!!"false" == true`.

**Comment by adam-azarchs** [comment]
Confirmed, you can work around this bug by setting
```yaml
sync-labels: ''
```
in your workflow.

**Comment by liverpool1026** [comment]
> Confirmed, you can work around this bug by setting
> 
> ```yaml
> sync-labels: ''
> ```
> 
> in your workflow.

Thanks for this, can also confirm this works in v4. Any plans to fix this properly in the next version?

**Comment by xSAVIKx** [comment]
This still may happen with v5 action if the labels are added by the user at the time that's very close to the action run:
<img width="416" alt="image" src="https://github.com/user-attachments/assets/e3a86c5a-9a3d-4085-87ba-fd760c27098b">

User added labels at `2024-07-19T15:07:34Z`. Bot added his own at `2024-07-19T15:07:35Z`.

And bot started running at `2024-07-19T15:07:34Z` as per GH action logs. So my guess is that it read labels, then user added his labels, then bot applied the rules and has overridden some of the labels the user has previously added.

WF config:
```
# .github/workflows/auto-labeler.yaml
name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [ opened, reopened, synchronize ]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/labeler@v5
        with:
          sync-labels: false
          dot: true
          configuration-path: .github/labeler.yaml
```

Related rules:
```
"/web":
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - SOME FILES
javascript:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - src/js/**
```
