### ISSUE TITLE
Not clear how to use the action

### ISSUE THREAD

**Issue by vimalk78** [actions/labeler#114]
It is not clear to me how do i use this action.

When i read the README, i understand that there has to be a file with the content
```
name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

and "somewhere" i must add the label-name and paths , like:
```
# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
- any: ['src/**/*.js']
  all: ['!src/main.js']
```

but what is the relation between the two? it is not clear at all to me

**Comment by imjohnbo** [comment]
Hi @vimalk78 👋 I'm another newbie to this action, but it appears you need a `.github/labeler.yml` file to define configuration like this:

```yaml
# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
- any: ['src/**/*.js']
  all: ['!src/main.js']
```

to accompany your workflow, which goes in `.github/workflows/whatever.yml`:

```yaml
name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

Example here: https://github.com/imjohnbo/labeler-test, see `pulls/1`
