### ISSUE TITLE
How to specify a list of simple wildcard globs?

### ISSUE THREAD

**Issue by Danl2620** [actions/labeler#120]
I'm struggling to find the syntax to test a PR against a simple list of wildcard globs. I'd like to label a PR that touches any file that matches *.cpp, *.h, *.py, *.cmd, or *.ps1. How do I format this?

I've tried

```
Changes - Code:
  - '*.cpp'
  - '*.h'
  - '*.c'
  - '*.py'
  - '*.cmd'
  - '*.ps1'
```

among several other formats -- none seem to pick up changes I expect.

A few questions:

1. How do I write the globs correctly?
2. How can I diagnose these failures? Are there debug or verbose options?
3. Is there a way to test/iterate locally (rather than push to github)?

**Comment by Danl2620** [comment]
Is it possible I need to do something to have the labeler add more than one label at a time? This thing is not operating as expected so I must be doing something awful.

Here is my action:

```
name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
```

And I have several label sections like above ^^^.
