### ISSUE TITLE
Action reporting `repo-token` is not supplied

### ISSUE THREAD

**Issue by dvprrsh** [actions/labeler#122]
```yaml
# .github/workflows/labeler.yml
name: PR Change Labeller
on:
  - pull_request_target

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

```

```yaml
# .github/labeler.yml
repo:
  - ./*
  - "!./package?(-lock).json"
src:
  - src/*
test:
  - src/__tests__/*
client:
  - src/client/**/*
server:
  - src/server/**/*
package:
  - ./package.json
```
Output:
```bash
Run actions/labeler@main
  with:
    configuration-path: .github/labeler.yml
    sync-labels: false
Error: Error: Input required and not supplied: repo-token
Error: Input required and not supplied: repo-token
```

Strangely it says it is running `actions/labeler@main` rather than v3. Don't know if that is to do with this issue or not. Any help would be greatly appreciated :)
