### ISSUE TITLE
Doesn't work anymore with dependabot

### ISSUE THREAD

**Issue by essenmitsosse** [actions/labeler#132]
There recently has been a [security update](https://t.co/f46DVovJRn) to how secrets work in PRs. This brakes current behaviour for [Dependabot](https://dependabot.com/), but there is currently a hotfix in the [dependabot issue](https://github.com/dependabot/dependabot-core/issues/3253), namely to add `pull_request_target`. For me this doesn't help and Labeler actions still fail since they can't access `GITHUB_TOKEN`.

My workflow
```yml
name: Labeler
on: [pull_request, pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

The GitHub Action output:
```
Run actions/labeler@v2
  with:
    repo-token: ***
    configuration-path: .github/labeler.yml
    sync-labels: false
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
```

It works fine for PRs opened by normal GitHub users, but fails on dependabot, since it can't access the token.
