### ISSUE TITLE
[BUG] HttpError: Resource not accessible by integration - but it's working at a 2nd call

### ISSUE THREAD

**Issue by joergi** [actions/labeler#136]
I was using the labeler quite a while now, so I can have nice labels for my mono-repo.
But since a few weeks I get always(~99%) the same errors (see below), when Dependabot is creating PRs with dependency updates.

If I rerun the check, everything works as expected.
Anyone else having this issue?

```
triage
HttpError: Resource not accessible by integration
```

```
triage
Resource not accessible by integration
```

My `.github/workflows/labeler.yml` looks like this:

```
name: "Pull Request Labeler"
on:
  pull_request:
    branches: [ main ]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
```
my `.github/labeler.yml` looks like this:
```
project1-frontend:
  - services/project1-frontend/**/*

project1-backend:
  - services/project1-backend/**/*
  
project2-frontend:
  - services/project2-frontend/**/*

project2-backend:
  - services/project2-backend/**/*
```
  

![image](https://user-images.githubusercontent.com/1439809/113893317-2df13280-97c7-11eb-9830-64f3f125ddc1.png)
