### ISSUE TITLE
sync-labels isn't working for removing labels

### ISSUE THREAD

**Issue by onx2** [actions/labeler#172]
The `sync-labels` option isn't working for me - perhaps I have it configured incorrectly? I added my configuration below and here is my repo folder structure:
- root_name
  - api
    - ... api files
  - web
    - ... web files
  - .github
  - README.md

When I change a file in `web`, it will add the `web` label; however, when I revert that change (`web` is no longer modified), it does not remove the label. 

**.github/labeler.yml**
```yml
web:
  - web/**/*
```

**.github/workflows/pr_label.yml**
```yml
on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize, edited, reopened]


jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v2
        with:
          sync-labels: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml

      - name: Require Labels
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "api, config, documentation, migration, web, bug, enhancement"

```
