### ISSUE TITLE
How to make the labeler.yml is unclear

### ISSUE THREAD

**Issue by logankilpatrick** [actions/labeler#18]
Please add a more robust example in the readme. It's unclear what the relationship between example and those other files is... 

I would suggest using file paths fortis repo to make the example more relevant.

**Comment by logankilpatrick** [comment]
Related to [this issue](https://github.com/actions/starter-workflows/issues/90)

**Comment by NobbZ** [comment]
In my opinion the README is clear.

You need a `.github/labeler.yml` in the repository which describes relationship between touched files and labels attached which is in the upper example and you need an action, which is in the bottom example.

**Comment by Twonki** [comment]
I also think the Readme is clear, but when you just go by the github-actions and choose labeler it's very unclear that you need the additional yaml.

**Comment by logankilpatrick** [comment]
Yes. That’s my thought as well.

Best, 
Logan Kilpatrick

**Comment by ethomson** [comment]
Thanks for the feedback.  I opened https://github.com/actions/starter-workflows/pull/167 to address this, since it's related to the starter worfklows experience.  I'm going to close this issue now and we'll follow up there.

Thanks again!

**Comment by vimalk78** [comment]
It is not clear to me as well.
When i read the README, i understand that there has to be a file with the content
```
name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

and "somewhere" i must add the label-name and paths , like:
```
# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
- any: ['src/**/*.js']
  all: ['!src/main.js']
```

but what is the relation between the two? it is not clear at all to me
