### ISSUE TITLE
Sequence not expected when running

### ISSUE THREAD

**Issue by CalvinWilkinson** [actions/labeler#204]
**Description:**
I have a YAML file that is using the labeler action and I am having some issues.

I am trying to add the label _**TRIAGE**_ to an issue or pull request that has been opened with any changes to anything the repository.

I tried the patterns below:
1. \*
2. **
3. .*
4. .*/
5. .**/**
6. **/**
7. ./**
8. ./
9. CASL/**

I did of course read the documentation but in my mind, some of these should of worked.  I could totally be doing something wrong.

I also tried:
``` yaml
TRIAGE: <all above patterns tried here>
```
and:
``` yaml
TRIAGE:
- <all above patterns tried here>
```
and:
``` yaml
TRIAGE:
- any: [ <all above patterns tried here>] 
```
and:
``` yaml
TRIAGE:
- any:
- <all above patterns tried here>
```

Here is my current YAML file

``` yaml
name: Triage PRs & Issues

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  TriageItem:
    runs-on: windows-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        TRIAGE:
        - "CASL/**"
```

---

**Current Behavior:**
The globbing patterns above not working.

**Comment by CalvinWilkinson** [comment]
Quick Update.

It was not obvious to me that the name of the job itself is the name of the label that you are dealing with.  I read the documentation but I just thought the example was using that name for the job name.  I could of simply misread and it was simply my fault. 

![image](https://user-images.githubusercontent.com/85414302/128743777-0af0bdd7-b490-4e08-9b50-7801d078f2bc.png)

I changed my YAML though and that issue went away, but have been presented with another one.
I used the YAML below and this is the error I get.

![image](https://user-images.githubusercontent.com/85414302/128744033-dc1865d4-7c7c-403b-8f41-12fd69cc25c1.png)

I don't understand this to be honest.  My old YAML had an open event with pull requests and issues but this new YAML only has a **on opened issues** event.  I open an issue and the workflow kicks off as expected, but the workflow does not fail.  I also do not get any labels added and the message is what I get in the logs.

**YAML Used:**
``` yaml
name: Triage PRs & Issues

on:
  issues:
    types: [opened]

jobs:
  TRIAGE:
    runs-on: windows-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```
