### ISSUE TITLE
Help to understand difference between any and all

### ISSUE THREAD

**Issue by BhautikChudasama** [actions/labeler#251]
I read documents, where I couldn't understand the difference between `any` and `all`.
Please correct me If I am wrong.
```yaml
# any means one, or two change, then the label is applied.
frontend:
  - any: ['frontend/one.js', 'frontend/two.js']
  
# all means must all condition is true, then the label is applied.
frontend:
  - all: ['frontend/one.js', 'frontend/two.js']
  
 # Is that any and below are the same?
frontend:
  - 'frontend/one.js'
  - 'frontend/two.js'
```
Thanks.
