### ISSUE TITLE
glob syntax is not intuitive, readme not specific enough

### ISSUE THREAD

**Issue by Gornoka** [actions/labeler#284]
In my opinion the readme does not specify clearly enough how globs should be specified, especially when they start with a wildcard.

~My problem was that " like it is used in the workflow definition yields to blobs being not recognized.~
 
~A comment in the readme , that using `"` (like in the action for branch filtering) instead of `'` will crash the action would be very nice to have.~
A comment that leading wildcards without " or ' will crash the action would be nice to have.
Kind regards 
Lukas

update: when testing more i found out that apparently sometimes " work, but i have no idea why they did not at other times.
the only thing that i have found that consistently does not work is blank globs without either ' or " and wildcards at the beginning.

````yml
#works
python:
- '**/*.py'
# crashes
# python:
# - **/*.py
# works
python:
- "**/*.py"
````
