### ISSUE TITLE
Labeler not triggering 'labeled' pull_request event type

### ISSUE THREAD

**Issue by mosherc** [actions/labeler#315]
I would like to perform some action when labeler labels my PR with a specific label. When I commit changes that trigger labeler, that is a pull_request synchronize type, but after the labeler runs, it does not trigger a labeled event so I can check what label is present and perform an action on that. I tried workflow_run but not getting anything working that way either, plus apparently there is no output from the action.

**Comment by bcowdery** [comment]
This is affecting me as well.

We have a label for high impact "Breaking Changes" that we apply to any PR that touches API specs and shared contracts. In addition to this label, I want to add a PR comment with some polite reminders and resources for the development team. 

Something like this:
```yaml
on:
  pull_request:
    types: [ labeled ]

jobs:
  breaking-changes:
    if: ${{ github.event.label.name == 'BREAKING CHANGES' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |  
          const message = `
            :fire: It looks like this PR contains **BREAKING CHANGES** to API docs, HTTP Clients or contracts.
          `
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          })
```

This works fine when the label is manually applied, but not when using the labeler action.

**Comment by irvv17** [comment]
Hi folks, I've been facing a similar issue, this actually works, but you'll need to use a Personal access token instead of the GitHub token provided just for the current action.

like so:
```
  add-stage-label:
    runs-on: ubuntu-latest
    needs: remove-build-label
    steps:
    - name: Add 🚀 Label
      uses: actions/labeler@v3
      with:
        repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        sync-labels: true
        configuration-path: .github/deploy-labeler.yml
```

**Comment by bcowdery** [comment]
> Hi folks, I've been facing a similar issue, this actually works, but you'll need to use a Personal access token instead of the GitHub token provided just for the current action.

@irvv17 Just to confirm, if you use a PAT then the labeler action does correctly trigger the `pull_request` `labeled` event in another workflow?

Also could you please share what permissions you used in your PAT? 

I wonder if this is just a case of a missing permission on the `GITHUB_TOKEN`. We could potentially work around the issue by [customizing the workflow permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token) and adding the missing permissions. My repo is configured with "permissive" workflow permissions (defaults to read/write for most scopes) - so im not sure what it could be missing...

Something like:
```yaml
permissions:
  contents: read
  pull-requests: write
```
