### ISSUE TITLE
Remove label when another has been added

### ISSUE THREAD

**Issue by MathieuMalfeyt-TomTom** [actions/labeler#339]
Question:
Is it possible to remove/not add a certain label when another label has been added from another path?

Configuration example:
docs: docs/*
automerge: '**/*.json'
workflow: .github/workflows/*

I would like to not have label automerge when there is also for example a docs or workflow label in the same PR.
So something like: if docs and or workflow label is there, don't add automerge label

**Comment by MaksimZhukov** [comment]
Hello @MathieuMalfeyt-TomTom ! 
You can negate globs (using `!` character) used to add other labels. Your configuration file may look like this:
```yml
docs:
- 'docs/**'

workflow:
- '.github/workflows/**'

automerge:
- any: ['**/*.json']
  all: ['!docs/**', '!.github/workflows/**']
```

In this case, the `automerge` label will be added if nothing changes in the `.github/workflows` and/or `docs` folders.
