### ISSUE TITLE
/github/workflow/event.json does not exist

### ISSUE THREAD

**Issue by jadeidev** [actions/labeler#346]
keep getting the following error
```
GITHUB_EVENT_PATH /github/workflow/event.json does not exist
GITHUB_EVENT_PATH /github/workflow/event.json does not exist
Could not get pull request number from context, exiting
```
with the following workflow
```yml
name: "PR Labeler"
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    container: ubuntu:latest
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```
any idea?
If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.
