### ISSUE TITLE
How can I add a label for any file change?

### ISSUE THREAD

**Issue by vikas027** [actions/labeler#362]
My labels for specific files and folders are working but I also want to add a label for any file change. Am I missing anything?

```yaml
---
# DOES NOT WORKS
seclabs:
- any: ['**/*', '*']

# WORKS
actions:
- '.github/**'
```
