### ISSUE TITLE
Could not get pull request number from context, exiting

### ISSUE THREAD

**Issue by PuneetKohli** [actions/labeler#37]
Similar to #25 I am getting the error "Could not get pull request number from context, exiting"

I tried playing around with a variety of things but could not get it to run.

**.github/labeler.yml:**

```
  # Add 'github' label to any change within the '.github' folder
github:
  - .github/*
  - .github/**/*

test:
  - lib/tests/*
  - lib/tests/**/*
  - multiview/src/test/*
  - multiview/src/test/*
```

**.github/workflows/push.yml**

```
on: push
name: On Push Workflow
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

Also tried with a repo specific token. v2.1.0, and combining with another workflow - no results.

**Comment by samajammin** [comment]
I'm having the same issue [here](https://github.com/ethereum/ethereum-org-website/runs/743268440?check_suite_focus=true).

**.github/labeler.yml**
```
'Status: Review Needed':
  - docs/**/*

'Type: Content':
  - docs/**/*.md

'Type: Design':
  - docs/**/*.styl

'Type: Documentation':
  - README.md

'Type: Tooling':
  - .github/**/*

'Type: Dependencies':
  - package.json

'Type: Translation':
  - docs/translations/**/*
  - docs/.vuepress/theme/utils/translations.js

```

**.github/workflows/labeler.yml**
```
name: Labeler
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
```
