### ISSUE TITLE
Labels not applied on PRs FROM forks

### ISSUE THREAD

**Issue by gregsdennis** [actions/labeler#399]
This is a bit related to #12 and #36, except that it's the other way around.

I have a repo (https://github.com/gregsdennis/json-everything), and the labeler always fails on PRs submitted by others ([example](https://github.com/gregsdennis/json-everything/pull/296)).

I expect that since the PR is in the primary repo, not the fork, it's should be getting my token (which works on all of _my_ PRs) and running the action with that.

**Comment by BitsOfAByte** [comment]
Can replicate this issue, all PRs coming into my repository from forks fail every time with `
HttpError: Resource not accessible by integration`

**Comment by Hans5958** [comment]
For these cases, `pull_request_target` should be used compared to `pull_request`.

**Comment by gregsdennis** [comment]
Sorry.  I'm finally getting around to updating this as I finally have an [external PR](https://github.com/gregsdennis/json-everything/pull/369).

The change to `pull_request_target` isn't working for me.  I even added the explicit permissions as you have in the README.

**Comment by gregsdennis** [comment]
Nevermind.  That example was a rebasing issue.  All is well.  Thanks for the pointers.

**Comment by remyleone** [comment]
I have an issue in this run: https://github.com/scaleway/terraform-provider-scaleway/actions/runs/17070268970/job/48397094646?pr=3269#step:3:9 
While having:

```
name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Labeler
        uses: actions/labeler@v5
```
