### ISSUE TITLE
Labels NOT applied

### ISSUE THREAD

**Issue by wojtekxtx** [actions/labeler#461]
My `.github/labeler.yml`:

```yml
RootFiles:
 - /*.yml
```

My `.github/worklows/label.yml`:

```yml
# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

My labels:
![Zrzut ekranu 2022-12-1 o 15 27 58](https://user-images.githubusercontent.com/109670049/205078369-7f2da015-49d5-4f44-b585-d9d0b15d34a6.png)

I want to apply `RootFiles` label to *any* `.yml` file inside *rootdir* `/` thats changed by `PR`.

Whats wrong?
