### ISSUE TITLE
Random numbers label applied to our PRs (bug?)

### ISSUE THREAD

**Issue by deep-cognite** [actions/labeler#467]
Hey!

We just enabled this GitHub workflow in our repo, and we get these bunch of weird numbers as labels on our PRs 😅 

<img width="890" alt="image" src="https://user-images.githubusercontent.com/70804363/207277861-a114a15b-474f-4fc5-b196-4b973792a31d.png">

Any idea why that's the case? 

This is our ".github/workflows/label.yml":
```yml
# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
```

and our ".github/labeler.yml":
```yml
repo
- "*"

testapp
- "apps/mock-server/**/*"
- "apps/my-app/**/*"
- "libs/mock-data/**/*"
```

**Comment by deep-cognite** [comment]
> Hello @deep-cognite! Thanks for reporting this! Could you please provide us with a link to the public repository so that we can try to reproduce the issue?

Unfortunately, its a private repository :/ 

Though, does the config/setup look correct to you? If it to any debug help, the repository is a NX monorepo 🤷

**Comment by MaksimZhukov** [comment]
@deep-cognite, you missed colon after label names. The following `labeler.yml` file should resolve the issue:
```yml
repo:
- "*"

testapp:
- "apps/mock-server/**/*"
- "apps/my-app/**/*"
- "libs/mock-data/**/*"
```

Please confirm if it works for you
