### ISSUE TITLE
Using template to install workflow results in broken action

### ISSUE THREAD

**Issue by dfandrich** [actions/labeler#492]
The workflow template suggested when installing actions/labeler from a project's "New workflow" button results in a workflow using the `pull_request` event (instead of `pull_request_target`) that causes issues such as #446, #399, #136 and others.

To reproduce, go to a project and choose the *Actions* tab. Click the *New workflow* button, enter `labeler` into the *Search workflows* box and click *Configure* in the *Label* entry. This is the template that's given to submit:

```yml
# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```
Note the use of `pull_request` instead of `pull_request_target`.
