### ISSUE TITLE
Support labeling based on the pull request/commit title and messages

### ISSUE THREAD

**Issue by XVilka** [actions/labeler#55]
To apply the label based on the pattern match in one of the fields in:
- PR title
- PR body
- PR commit title
- PR commit body

**Comment by austince** [comment]
The commit-specific matching might be more work, as it would require fetching all the commits that are contained in the PR, but the PR title and body should be already available.

What about adding a config object `pr: { body?: StringOrMatchConfig, title?: StringOrMatchConfig }`?

Ex:
```yaml
# Add 'test' label to any change to *.spec.js files within the source dir
# or with a PR title that is in the form 'test:*'
# or with a PR body that contains the word 'test' but not 'bug'
test:
 - src/**/*.spec.js
 - pr:
     title:
       - 'test:*'
     body:
       - any: [ '*test*' ]
         all: [ '*bug*' ]
```

This could then be expanded to include the commits:

```yaml
# Add 'test' label to any change to *.spec.js files within the source dir
# or with a PR title that is in the form 'test:*'
# or with a PR body that contains the word 'test' but not 'bug'
# or has any commits with a title in the form 'test:*'
test:
 - src/**/*.spec.js
 - pr:
     title:
       - 'test:*'
     body:
       - any: [ '*test*' ]
         all: [ '*bug*' ]
- commits:
    title:
      - 'test:*'
```
