### ISSUE TITLE
Unable to resolve action `actions/labeler@v4.2.0`, unable to find version `v4.2.0`

### ISSUE THREAD

**Issue by ekosman** [actions/labeler#605]
I want to use the outputs of a labeler step in order to selectively run tests based on the added labels. For this, I understand I need v4.2.0. However, I get the following error:
```
Unable to resolve action `actions/labeler@v4.2.0`, unable to find version `v4.2.0`
```

Additionally, I think there is a mistake in README. It says install `v3`:
```
    steps:
    - id: label-the-PR
      uses: actions/labeler@v3
```

**Comment by dusan-trickovic** [comment]
Hello @ekosman ! Thank you for creating this issue. We will investigate it and see what can be done :)

**Comment by MaksimZhukov** [comment]
Hello @ekosman!
I could not reproduce your issue, I was able to use the `v4.2.0` tag. Could you please provide us with a link to your workflow run? 

Have you tried using the `v4` tag? It points to the same commit as `v4.2.0`.

Thank you for noticing a typo in the documentation. We are fixing it in this [pull request](https://github.com/actions/labeler/pull/606).

**Comment by ekosman** [comment]
> Hello @ekosman! I could not reproduce your issue, I was able to use the `v4.2.0` tag. Could you please provide us with a link to your workflow run?
> 
> Have you tried using the `v4` tag? It points to the same commit as `v4.2.0`.
> 
> Thank you for noticing a typo in the documentation. We are fixing it in this [pull request](https://github.com/actions/labeler/pull/606).

Thanks! Unfortunately, I can't share the workflow run here but for instance I have this snipper in my yml file:

```
    steps:
      - name: Label and comment PR size
        if: github.event_name == 'pull_request'
        uses: boschresearch/pr-size-labeler@v3.0.0
        # Uncomment these if you want to use your own custom configuration
        #with:
        #  bucketConfigFile: "<PATH_TO_YOUR_BUCKET_CONFIG>"

      - name: Label type
        id: label-the-PR
        if: github.event_name == 'pull_request'
        uses: actions/labeler@v4

      - name: print labels
        run: |
          echo ${{ steps.label-the-PR.outputs.all-labels }}
```

In the PR, I see the added labels:
![image](https://github.com/actions/labeler/assets/10260165/6e371541-e835-4cc7-b102-a98ee79ed081)


However, when checking the output of `print labels` step, I see nothing:
![image](https://github.com/actions/labeler/assets/10260165/7872e4b2-eb97-4ae4-b578-0e06012fda65)
