### ISSUE TITLE
No label added to PR

### ISSUE THREAD

**Issue by npitsillos** [actions/labeler#61]
Hello I do believe the issue is relevant because it seems to me this is a bug.  I apologise if this is not really.  But I create a .github/workflows/labeler.yml for the workflow and another .github/labeler.yml defining the labels but the PR's are not labeled even though the check passes.

.github/labeler.yml
```
repo:
  - ./*

feature:
  - talos/*

documentation:
  - ./*.md
```

.github/workflows/labeler.yml
```
name: PR Labeler
on:
  pull_request:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```
