### ISSUE TITLE
Bug with files in root folder

### ISSUE THREAD

**Issue by e1iman** [actions/labeler#627]
**Description:**
Config for files in root folder
```
"dev: yes":
    - any: ['**/*.cs']

"dev: no":
    - any: ['!**/*.cs']

"changelog: yes":
    - any: ['CHANGELOG.md']

"changelog: no":
    - any: ['!CHANGELOG.md']
```

This works perfectly when PR doesnt contain `.cs` file changes, then only label `dev:no` is pushed

While if there is no change in `CHANGELOG.md` file, both labels `changelog: yes` and `changelog: no` are added.

<img width="724" alt="image" src="https://github.com/actions/labeler/assets/13000400/c246f2e3-3ff1-4d4d-9a67-014d0cdd3449">

**Action version:**

i use @v4 version

here is my yaml file
```
            -   name: Label pull requests
                uses: actions/labeler@v4
                with:
                    sync-labels: true
```

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Repro steps:**  
Repro steps are basically in description above

**Expected behavior:**
I should see label `changelog: yes` only if there is changes done in `CHANGELOG.md` file

**Actual behavior:**
I see label `changelog: yes` added together with `changelog: no` while my PR doesnt have changes in `CHANGELOG.md` file
