### ISSUE TITLE
Labeler not running at all

### ISSUE THREAD

**Issue by Robinnnnn** [actions/labeler#638]
**Description:**
The labeler workflow is simply not running at all for this pull request: https://github.com/gallery-so/gallery/pull/1726

**Action version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
- Visit https://github.com/gallery-so/gallery/pull/1726
- Examine rules used:

.github/labeler.yml
```
web:
  - apps/web/**

mobile:
  - apps/mobile/**

shared:
  - packages/shared/**
```

.github/workflows/labeler.yml (taken from README)
```
name: 'Pull Request Labeler'
on:
  - pull_request (also tried pull_request_target)

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
```

**Expected behavior:**
the labeler workflow should be triggered

**Actual behavior:**
no workflow is being triggered
