### ISSUE TITLE
Multiple path matches are not correctly displayed as a label

### ISSUE THREAD

**Issue by leonsteinhaeuser** [actions/labeler#641]
**Description:**

I have a repository that contains IaC files for different environments and deployments. I want to label my pull requests based on some criteria. For example:

- provider
- zone
- k8s dev, staging, production environment
- cluster change
- deployment change
- ...

example labeler.yml:

```yaml
'provider/aws':
  - deployments/aws/**
  - clusters/aws/**

'zone/aws/eu-central-1':
  - deployments/aws/eu-central-1/**
  - clusters/aws/eu-central-1/**

'zone/aws/us-east-1':
  - deployments/aws/us-east-1/**
  - clusters/aws/us-east-1/**

'k8s/dev':
  - clusters/aws/*/dev/**

'k8s/staging':
  - clusters/aws/*/staging/**

'k8s/production':
  - clusters/aws/*/production/**

'k8s':
  - clusters/**

'deployments/dev':
  - deployments/aws/*/dev/**

'deployments/staging':
  - deployments/aws/*/staging/**

'deployments/production':
  - deployments/aws/*/production/** 
```

**Action version:**

`actions/labeler@v4`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

Define a workflow with the following configuration:

```yaml
name: Pull Request Labels

on: pull_request

jobs:
  folder-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          sync-labels: ''
```

Create a new pull request with the changes below:

![labeler_files_changed](https://github.com/actions/labeler/assets/42437185/54d900ca-a329-45d2-bd50-e4551612f38a)

**Expected behavior:**

I would expect the following labels to be set:

- `provider/aws`
- `zone/aws/eu-central-1`
- `k8s/dev`
- `k8s/staging`
- `k8s/production`
- `k8s`
- `deployments/dev`
- `deployments/staging`
- `deployments/production`

**Actual behavior:**

![labeler_pr_assigned_labels](https://github.com/actions/labeler/assets/42437185/d1bc7c74-42df-47ef-b722-8295127733e2)

- `provider/aws`
- `zone/aws/eu-central-1`
- `deployments/dev`
- `deployments/staging`
- `deployments/production`
