### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by duffzm** [actions/labeler#662]
**Description:**
I'm not seeing any output (`new-labels`, `all-labels`) from use of the action. Otherwise, my labels are being synchronized correctly.

**Action version:**
v4 (note that @v4.3.0 shows as not found for me, not sure if it matters)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  

```yaml
jobs:
  setup:
    runs-on: [ self-hosted, ECSRunner]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add Labels
        id: add-label
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.CICD_PAT }}
          sync-labels: true
      - name: Print all labels
        run: |
          echo "${{ toJSON(steps.add-label.outputs) }}"
          echo "${{ steps.add-label.outputs }}"
          echo "${{ steps.add-label.outputs.all-labels }}"
          echo "${{ steps.add-label.outputs.new-labels }}"
          echo "${{ toJSON(steps.add-label.outputs.all-labels) }}"
```

labeler.yml file

```yaml
AnyChange:
  - '**'
  
MyOtherLabels:
  - 'app/**'
  
 etc.
```
**Expected behavior:**
I expect to have non null ouput containing sync'd label values.

**Actual behavior:**
this 
```yaml
jobs:
  setup:
    runs-on: [ self-hosted, NoDocker ]
    outputs:
      timeout_minutes: ${{ env.TIMEOUT_MINUTES }}
      pr_labels: ${{ env.PR_LABELS }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Job Init
        uses: data-products-and-platforms/actions/job-init@main
      - name: Add Labels
        id: add-label
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.CICD_PAT }}
          sync-labels: true
      - name: Print all labels
        run: |
          echo "${{ toJSON(steps.add-label.outputs) }}"
          echo "${{ steps.add-label.outputs }}"
          echo "${{ steps.add-label.outputs.all-labels }}"
          echo "${{ steps.add-label.outputs.new-labels }}"
          echo "${{ toJSON(steps.add-label.outputs.all-labels) }}"
```
results in:
```
0s
Run echo "{}"
  echo "{}"
  echo "Object"
  echo ""
  echo ""
  echo "null"
  shell: /bin/bash -e {0}
{}
Object


null
```
but labeling is working
<img width="132" alt="image" src="https://github.com/actions/labeler/assets/52840376/fd106b8c-241d-4b92-bafe-b84836d03004">
