### ISSUE TITLE
found unexpected type for label 'xxxxxxxx' (should be array of config options)

### ISSUE THREAD

**Issue by danielmayor** [actions/labeler#710]
**Description:**
Somehow, today the labeler action started to fail. I didn't change any labeler config file or setup. I wonder if it's because of the new release ([v5.0.0](https://github.com/actions/labeler/releases/tag/v5.0.0)).

Execution output:
```
Run actions/labeler@master
  with:
    repo-token: ***
    configuration-path: .github/labeler.yml
    sync-labels: false
    dot: true
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Error: Error: found unexpected type for label 'frontend' (should be array of config options)
Error: found unexpected type for label 'frontend' (should be array of config options)
```

.github/labeler.yml:
```
frontend:
  - shared/frontend/**/*

pdf:
  - shared/pdf/**/*

configurations:
  - .circleci/**/*
  - .github/**/*
 ```

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
The action runs automatically every time I create a PR. The `labeler.yml` hasn't any changes.

**Expected behavior:**
Action should run successfully.

**Actual behavior:**
I get this error: `Error: Error: found unexpected type for label 'frontend' (should be array of config options)`

**Comment by HorizonNet** [comment]
I would tend to say that the documentation is not correct. I'm running into the same problem mentioned in the description, having the following labeler configuration (please note that I tried different variations)

```yaml
terraform:
  - changed-files:
    - any-glob-to-any-file: terraform/**
```

Which to me looks similar to the following snippet from the documentation mentioned above

```yaml
Documentation:
- changed-files:
  - any-glob-to-any-file: docs/*
```

The workflow definition is also similar to what I've seen in the documentation

```yaml
---
name: Pull Request Labeler

on:
  pull_request_target:

jobs:
  triage:
    name: Label triage

    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/labeler@v5.0.0
        with:
          sync-labels: true
```

Am I missing something?
