### ISSUE TITLE
Sync not working on labels with exceptions

### ISSUE THREAD

**Issue by Chefski** [actions/labeler#713]
**Description:**
Sync doesn't seem to work for the directories which a label has exceptions in (partially. It removed one label). Maybe my file is setup wrong but some labels remain after there are no changes to a PR.
![Xnip2023-12-06_23-59-05](https://github.com/actions/labeler/assets/100310118/80e6f1b3-d30b-4d6b-b25d-a6378e4d56e2)

The remaining labels in the screenshot are `code` and `icons`.

Maybe I'm testing it too extremely? Or it's just setup incorrectly

**Action version:**
5.0.0

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Repro steps:**  
Testing on a private test repo but here is the [public repo](https://github.com/LawnchairLauncher/lawnicons) if it helps.

```
name: "Label PRs"

on:
  - pull_request_target

jobs:
  label-prs:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          sync-labels: true

```

```
docs:
  - changed-files:
    - any-glob-to-any-file: '*.md'
    - any-glob-to-any-file: .github/PULL_REQUEST_TEMPLATE/*.md
    - any-glob-to-any-file: .github/pull_request_template.md
    - any-glob-to-any-file: docs/**

icons:
  - changed-files:
    - any-glob-to-any-file: svgs/*
    - any-glob-to-any-file: app/assets/appfilter.xml

code:
  - all:
  - changed-files: # Not indented as it either had the same or better results
    - any-glob-to-any-file: 'app/**'
    - any-glob-to-all-files: '!app/src/main/res/*/strings.xml'
    - any-glob-to-all-files: '!app/assets/appfilter.xml'


locale:
  - changed-files:
    - any-glob-to-any-file: app/src/main/res/*/strings.xml
    
```

**Expected behavior:**
Each label will be removed after all changes have been removed.

**Actual behavior:**
Labels remain even after the PR has no changed files (only `code`, `icons` and/or `locale`
