### ISSUE TITLE
example fails yaml validation

### ISSUE THREAD

**Issue by boneskull** [actions/labeler#746]
**Description:**

The example in the README fails YAML schema validation in VSCode

**Action version:**

v5.0.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

1. Create a new `labeler.yml` in `.github`
2. Paste this (from the example):
    ```yaml
    # Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
    source:
    - all:
      - changed-files:
        - any-glob-to-any-file: 'src/**/*'
        - all-globs-to-all-files: '!src/docs/*'
    ```
3. See error: ![image](https://github.com/actions/labeler/assets/924465/f8a805dd-e853-4d3e-8d09-b7ee6daf2e2c) ![image](https://github.com/actions/labeler/assets/924465/ffe8b444-056e-493b-a6e8-f2a3b1e6dfce) 

**Expected behavior:**
No validation error

**Actual behavior:**
See screenshots
