### ISSUE TITLE
Node 16 gets warning

### ISSUE THREAD

**Issue by tobolar** [actions/labeler#754]
**Description:**
In the CT process, I geth the following warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/labeler@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

My CI process:
```
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: false
```
**Justification:**
The github (abovementioned link) says:
> For self-hosted runner administrators:
> Update your self-hosted runners to runner version [v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) or later to ensure compatibility with Node 20 actions.

**Are you willing to submit a PR?**
No
