### ISSUE TITLE
Could not find pull request warning for pull_request closed event

### ISSUE THREAD

**Issue by convers39** [actions/labeler#775]
**Description:**

I need to run a workflow after a PR is closed or merged. So I set the `types` as `closed`. Now the issue is since the PR is closed first in order to trigger the workflow, labeler seems not able to find a closed PR and gives me a warning message of `Could not find pull request <number>, skipping`. I have some tasks which rely on labeler, so wonder if there is any way to work with closed PRs.

```yml
on:
  pull_request:
    types: [ closed ]
jobs:
  delete_channel:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # ...
      - id: pr_labels
        uses: actions/labeler@v5

```

<img width="879" alt="image" src="https://github.com/actions/labeler/assets/42597395/5a4e6626-2680-4433-8144-ac2dcfdb4d5c">

**Action version:**
Specify the action version

v5

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Repro steps:**  

basically the action file I posted 

**Expected behavior:**

Possible to deal with closed PRs.

**Actual behavior:**

`Could not find pull request <number>, skipping` warning, and the following steps are skipped.
