### ISSUE TITLE
Update documentation to note that you can use sentences in labels

### ISSUE THREAD

**Issue by mofosyne** [actions/labeler#780]
https://github.com/Prowlarr/Prowlarr/blob/develop/.github/labeler.yml

Was able to see that you are allowed to do this:

```
'Area: API':
  - changed-files:
      - any-glob-to-any-file:
          - src/Prowlarr.Api.V1/**/*

'Area: Db-migration':
  - changed-files:
      - any-glob-to-any-file:
          - src/NzbDrone.Core/Datastore/Migration/*
```

And that you are no restricted to only alphanumeric no space labels. This would have been handy to know in the readme.
