### ISSUE TITLE
Allow for only applying a label if another label has not been applied (enumerated labels)

### ISSUE THREAD

**Issue by mofosyne** [actions/labeler#781]
Was experimenting with 

```yaml
"review complexity : high":
    - changed-files:
        - any-glob-to-any-file:
            - ggml-cuda/**
            - ggml-vulkan.cpp
            - ggml_vk_generate_shaders.py
"review complexity : medium":
    - changed-files:
        - any-glob-to-any-file:
            - .devops/**
            - .github/**
            - ci/**
#'review complexity : low':
...
```

But realised that there is a possibility that multiple of these tags can apply at the same time. I would like the ability to not label if another label (or in my context a higher priority label) has already been matched.

I hope to also combine it with https://github.com/actions/labeler/issues/486 for a more robust review complexity estimating labeler
