### ISSUE TITLE
Having difficulty creating my globs

### ISSUE THREAD

**Issue by LimesKey** [actions/labeler#801]
Sorry, not a bug report, I just couldn't find another place to post this.

I'm hoping to issue 3 labels to pull requests for my repo, one for 'Submission', 'Dev' and 'Invalid'. Having a little trouble understanding how to create globs, I've asked ChatGPT several times but I seem to be getting back code with syntax errors and nothing like what's in the README.

### Submission
The Submission label should be applied if there are changes to the `/projects` directory but NOT if there are changes in other top-level directories and or in their subfolders, other than `/projects` of course.

### Dev
This should almost be the reverse of 'Submission', which should apply when there are changes to any root directories and their subfolders but NOT when there are changes to the folder or any subfolders in the `/projects` directory.

### Invalid
This should apply if there are changes in `/projects` AND in any other top-level directories (other than /projects) and their subdirectories.

Here's my current `labeler.yml`
```yml
Invalid:
- all:
  - changed-files:
    - any-glob-to-any-file: '*'
    - all-globs-to-any-file: 'projects/**'

# Add 'Submission' label to any changes within '/projects' folder or any subfolders
Submission:
- changed-files:
  - any-glob-to-any-file: 'projects/**'

Dev:
- all:
  - changed-files:
    - any-glob-to-any-file: '*'
    - all-globs-to-any-file: '!projects/**'
```
Currently, when there are changed files in the top level directory and in the `/projects` folder the `Dev` and `Invalid` label apply when the `Invalid` label should only be applied. The `Dev` and `Invalid` label should never be applied at the same time.

**Comment by HarithaVattikuti** [comment]
Hello @LimesKey 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by sameershelar-paypay** [comment]
I m also facing this issue, Looks the the exclusion is not working as expected.
```
Label:
  - changed-files:
      - any-glob-to-any-file: libs/a1/**
      - any-glob-to-any-file: libs/a2/**
      - all-globs-to-all-files: '!libs/a1/**/*XX*'
      - all-globs-to-all-files: '!libs/a2/**/*XX*'
```

In this case the label should not be added if the changed file is present in `libs/a1` or `libs/a2` and the file name contains `XX` keyword.

But the label is being added for any change.

**Comment by sebastian-nowak** [comment]
@sameershelar-paypay, you're missing the top-level '- all:'. If you skip it, it defaults to 'any'.

**Comment by artpelling** [comment]
I am having similar issues with the exclusion not working.

> Here's my current `labeler.yml`


Shouldn't one use `all-globs-to-ALL-files` as suggested in the example section of the `README.md`?

**Comment by artpelling** [comment]
@HarithaVattikuti Is there any update on this? I've used the exclusion as demonstrated in the example section but it does not work.

**Comment by suyashgaonkar** [comment]
Hi @LimesKey , We did work on your request from the provided details we would suggest to pass a comma seperated list of globs for Dev and Invalid invdividually to achieve desired result. Dev and Submission label wont come together as they are reverse of each other, but same cannot be said for Dev and Invalid because the conditions mentioned for the Invalid covers all the cases for Dev label which basically makes Dev a subset of Invalid.
You can refer to the following [url](https://github.com/actions/labeler?tab=readme-ov-file#basic-examples) in the README for more information.

**Comment by artpelling** [comment]
> Hi @LimesKey , We did work on your request from the provided details we would suggest to pass a comma seperated list of globs for Dev and Invalid invdividually to achieve desired result. Dev and Submission label wont come together as they are reverse of each other, but same cannot be said for Dev and Invalid because the conditions mentioned for the Invalid covers all the cases for Dev label which basically makes Dev a subset of Invalid. You can refer to the following [url](https://github.com/actions/labeler?tab=readme-ov-file#basic-examples) in the README for more information.

Thanks. Could you provide an example of a working list?

As I see it, the syntax used by @LimesKey is like suggested in the README, except that he uses `all-globs-to-ANY-files`. In the README it says:
```
# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
- all:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'
    - all-globs-to-all-files: '!src/docs/*'
  ```

**Comment by suyashgaonkar** [comment]
Hi @artpelling , you can refer to following code snippet.
**Example 1 :-** 
```
Invalid:
- all:
   - changed-files:
     - any-glob-to-any-file: 'projects/**'
     - all-globs-to-any-file: 'projects/**'

Dev:
- all:
  - changed-files:
    - any-glob-to-any-file: '*'
    - all-globs-to-any-file: '!projects/**'

Submission:
 - changed-files:
   - any-glob-to-any-file: ['list', 'of', 'globs'] #list of globs where any file changes to specified folder will put a label.
```

**Example 2 :- Passing two seperate list for Dev and Invalid labels**


```
Invalid:
- all:
   - changed-files:
     - any-glob-to-any-file: 'projects/**'
     - all-globs-to-any-file: 'projects/**'

Dev:
- all:
  - changed-files:
    - any-glob-to-any-file:  ['list', 'of', 'globs'] #list of globs where any file changes to specified folder will put a Dev label

Submission:
 - changed-files:
   - any-glob-to-any-file: ['list', 'of', 'globs'] #list of globs where any file changes to specified folder will put a Invalid label
```

Note :- Do not enter path to Project folder to any of the comma seperated list as it is already covered in **Invalid** label configurations"

**Comment by LimesKey** [comment]
Thanks for your reply, and thanks for the example but it doesn't seem to apply to exactly what I asked. I'm still a little confused, are you able to send a config for what I was trying to do?

**Comment by suyashgaonkar** [comment]
Hi @LimesKey , apologies for the confusion regarding the solution. Consider the folder structure in the screenshot as an example. We recommend creating two separate comma-separated lists for the Dev and Invalid labels. The Invalid label should apply if there are changes in /projects and in any other top-level directories (other than /projects) and their subdirectories. The Dev label should apply when there are changes to any root directories and their subfolders, but not when there are changes to the folder or any subfolders in the /projects directory, making it almost the opposite of Submission. Therefore, all non-projects folders would get labeled under both Dev and Invalid. It is not possible for both labels to never be applied at the same time. 
Following is the solution we recommend considering the example in the screenshot.

```
Submission:
- changed-files:
  - any-glob-to-any-file: 'projects/**'

Dev:
  - changed-files:
    - any-glob-to-any-file: ['java/*','frontend/*']

Invalid:
  - changed-files:
    - any-glob-to-any-file: ['python/*','server/*']
```
