### ISSUE TITLE
Error: found unexpected type for label '<label>' (should be array of config options)

### ISSUE THREAD

**Issue by coilysiren** [actions/labeler#818]
**Description:**

I suspect that I'm just getting the labeler syntax wrong, but unfortunately I can't get it to work. Some assistance would be appreciated.

I'm getting the same error message as https://github.com/actions/labeler/issues/716

**Action v5:**

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

.github/workflows/labeler.yml

```yml
name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  label:
    name: Labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Uploads repository content to the runner
        with:
          sparse-checkout: |
            .github
      - uses: actions/labeler@v5
```

.github/labeler.yml

```yml
- any:
    - changed-files:
        - javascript: ["**/*.js", "**/*.jsx"]
        - typescript: ["**/*.ts", "**/*.tsx"]
        - python: ["**/*.py"]
        - terraform: ["**/*.tf"]
        - shell: ["**/*.sh"]
        - api: ["api/**/*"]
        - frontend: ["frontend/**/*"]
        - analytics: ["analytics/**/*"]
        - ci/cd: [".github/workflows/**/*", "bin/**/*", "**/*/Makefile"]
        - documentation: ["documentation/**/*", "**/*.md"]
        - infra: ["infra/**/*"]
        - database: ["api/src/db/**/*"]
        - openapi: ["api/openapi.generated.yaml"]
        - storybook: ["frontend/stories/**/*", "frontend/.storybook/**/*"]
```

https://github.com/HHS/simpler-grants-gov/pull/2774

**Expected behavior:**

Labels are added. Or at least, CI doesn't fail.

**Actual behavior:**

> Error: found unexpected type for label 'javascript' (should be array of config options)
