### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ojedavidea** [actions/labeler#84]
.

**Comment by ojedavidea** [comment]
is there any tutorial in understandable english to help create actions (automations) for :
- attributing milestone(s) to a pull request upon specific editing (related to specific line(s) in the file or to specific expression newly added) of a specific repository file ;
- attributing label(s) to a pull request upon specific editing (related to specific line(s) in the file or to specific expression newly added) of a specific repository file ;
- attributing project element(s) to a pull request upon specific editing (related to specific line(s) in the file or to specific expression newly added) of a specific repository file.

**Comment by ojedavidea** [comment]
What am I doing wrong please ?

```
# This is a basic workflow to help you get started with Actions

name: test29

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ issue ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: check the value for name
      run: |
           .....               # check the name value, if it's not 'Octocat', exit 1 to fail the workflow.
    # Runs a set of commands using the runners shell
    - name: add label and milestone    # will be executed when name value is correct
      run: |
           curl --request PATCH \
                --url ${{ github.event.pull_request.issue_url }} \
                --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
                --data '{"milestone": 1, "labels": [ "bug" ]}'      # 1 is the milestone number
```
