### ISSUE TITLE
HttpError: You do not have permission to create labels on this repository

### ISSUE THREAD

**Issue by matejchalk** [actions/labeler#870]
**Description:**
The labeler actions just started failing with: 

```
HttpError: You do not have permission to create labels on this repository.: {"resource":"Repository","field":"label","code":"unauthorized"}
```

Up until just now, the following workflow was working fine (see [runs](https://github.com/code-pushup/cli/actions/workflows/pr-labeler.yml)):

```yml
name: PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  label:
    name: Add PR labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true
```

**Action version:**

[v5](https://github.com/actions/labeler/releases/tag/v5)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

See PR https://github.com/code-pushup/cli/pull/1006 with [failing workflow](https://github.com/code-pushup/cli/actions/runs/15021843109/job/42212766588?pr=1006).

**Expected behavior:**

Action should have permission to create labels, since the built-in `GITHUB_TOKEN` secret is being used an `pull-requests: write` permissions are configured.

**Actual behavior:**

Workflow fails with permissions error:

![Image](https://github.com/user-attachments/assets/885d7f16-068e-40cc-a0eb-1e092379205a)
